{ config, pkgs, ... }: {
  imports = [
    ./configuration.nix
  ];
	wsl = {
		enable = true;
		defaultUser = "anna";
		startMenuLaunchers = true;
    wslConf = {  # /etc/wsl.conf
      network = { 
        generateResolvConf = false; #/etc/resolv.confv
      };
      interop = {
        appendWindowsPath=false;
        enabled = false;
      };
	  };      
  };
  # gotta do this ourselves
  environment.etc."resolv.conf".text = "
# This file was automatically generated by wsl.nix. Control it from the nix file.

nameserver 8.8.8.8
";


}